version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: clamosbotDB
    restart: always
    environment:
      POSTGRES_USER: clamosbot
      POSTGRES_PASSWORD: "86e=WxayV3eK"
      POSTGRES_DB: clamosbotDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
